### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by russellhealy** [imathis/hsl-picker#15]
This is awesome! It would be great if you added optional text on top of the foreground: "Text" or something, which could be colored independently, much like you do for foreground/background. I would like to be able to test text colors against background colors.

Thank you for such a great tool!

**Comment by imathis** [comment]
Thanks for the id idea! I agree that would be useful and while I would like to make some color picking tools which made that easier, I think setting text has quite a few variables and would probably warrant a dedicated mode. I'll consider this for the future, but with the current focus of this tool I don't think this will be implemented.

Also check it out, the site has been completely rewritten from scratch and now has HWB color modes.
