### ISSUE TITLE
URL input field won't update on "Random".

### ISSUE THREAD

**Issue by dnunes** [imathis/hsl-picker#8]
When you click the "random" button the URL input field at the footer won't update itself until the next click event.

Steps:
1) Choose a color dragging the sliders.
2) Look at the Hex field. Compare with the URL input field. They are the same.
3) Click the "random" button.
4) Look at the URL input field. The value is still the same, although the Hex field has been updated.
5) Click anywhere in the page. The URL input field gets updated.

**Comment by imathis** [comment]
Thanks for the report. I've updated this to a new version and for now the random button is gone. Should I add it back this will be fixed though.
